### ISSUE TITLE
Type inference issue: `content` property missing from document type in v0.9.0

### ISSUE THREAD

**Issue by shrry2** [sdorra/content-collections#593]
Hi! Thank you for creating and maintaining content-collections. 
I'd like to report an issue we encountered after upgrading to v0.9.0.

## Description

After upgrading from v0.8.2 to v0.9.0, TypeScript no longer recognizes the `content` property on documents retrieved via `context.documents()`, even though the property exists at runtime.

## Environment

- `@content-collections/core`: ~0.9.0
- TypeScript: ~5.8.2

## Steps to Reproduce

1. Define a collection with the default parser (frontmatter):

```typescript
const shortcodes = defineCollection({
  name: "shortcodes",
  directory: "content",
  include: "**/*.md",
  schema: z.object({
    key: z.string(),
  }),
});
```

2. Try to access the `content` property in a transform function:

```typescript
const articles = defineCollection({
  name: "articles",
  directory: "content",
  include: "articles/**/*.md",
  schema: z.object({
    title: z.string(),
  }),
  transform: async (doc, context) => {
    const allShortcodes = await context
      .documents(shortcodes)
      .map((shortcode) => ({
        key: shortcode.key,
        content: shortcode.content, // TS2339: Property content does not exist on type { key: string; }
      }));


    console.log("All shortcodes:", allShortcodes);
    // => shortcode.content exists

    // replace shortcodes...
    
    return doc;
  },
});
```

## Expected Behavior

The `content` property should be available in the TypeScript type definition since:
1. The default frontmatter parser has `hasContent: true`
2. The property exists at runtime (verified with `console.log`)
3. This worked correctly in v0.8.x

## Actual Behavior

TypeScript error: `Property 'content' does not exist on type '{ key: string; }'`

## Additional Context

- The official documentation at https://www.content-collections.dev/docs/transform#access-other-collections doesn't mention this breaking change
- The runtime behavior is correct (content property exists), but the TypeScript type inference fails
- Current workaround requires explicit type casting: `(shortcode as { content?: string }).content`

## Possible Cause

Looking at the type definitions, it seems the conditional type that adds the `content` property based on `HasContent<TParser>` is not properly resolved when accessing documents through `context.documents()`.

**Comment by sdorra** [comment]
This looks like a bug. I will fix it.

**Comment by sdorra** [comment]
@shrry2 could you please test the following pre release of `@content-collections/core`?

```json
{
   "@content-collections/core": "https://pkg.pr.new/sdorra/content-collections/@content-collections/core@594"
}
```

**Comment by shrry2** [comment]
@sdorra Thank you so much for the incredibly quick fix! 

I tested the updated version and can confirm that the TypeScript errors are resolved and the build is working perfectly.

Really appreciate you taking the time to address this over the weekend – that's amazing support!
